#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


# BSPWM config

bspc monitor -d 1 2 3 4

bspc config window_gap 8
bspc config border_width 3
bspc config normal_border_color "#32344a"
bspc config focused_border_color "#787c99"
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config normal_border_color '#111111'
bspc config focused_border_color '#2596be'
xsetroot -cursor_name left_ptr &

# focus on hover
bspc config focus_follows_pointer true




# BSPWM rule

bspc rule -r *:*

## 1 > terminal
bspc rule -a Alacritty desktop='^1' follow=on focus=on

## 2 > web
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on
bspc rule -a google-chrome-stable desktop='^2' follow=on focus=on
bspc rule -a Google-chrome desktop='^2' follow=on focus=on

# bspc rule -a Alacritty desktop='^2'
bspc rule -a Zathura state=tiled

## Always Floating Apps
bspc rule -a Alacritty-Floating state=floating follow=on focus=on
bspc rule -a Thunar state=floating follow=on focus=on



# run on startup
flameshot &
picom -b --config $HOME/.config/picom/picom.conf

$HOME/.config/polybar/launch.sh
$HOME/.local/bin/scripts/run_on_boot &
$HOME/.local/bin/scripts/locker

